name: WebGL build and deploy development build on Itch.io

on:
  workflow_call:
    inputs:
      development_build:
        required: true
        type: boolean
    secrets:
      TELEGRAM_SESSION:
        required: true
      TELEGRAM_API_ID:
        required: true
      TELEGRAM_API_HASH:
        required: true
      TELEGRAM_CHAT_ID:
        required: true
      TELEGRAM_TOKEN:
        required: true
      UNITY_LICENSE:
        required: true
      ITCH_BUTLER_CREDENTIALS:
        required: true
      ITCH_GAME:
        required: true
      ITCH_USER:
        required: true

env:
  platform: WebGL
  itch_channel: HTML5

jobs:
  sendTagAnnotations:
    name: Send information to Telegram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Send notification message that build process started
        uses: mnicolas94/UnityCICDWorkflows/.github/actions/initial-message@v1-pre-13
        with:
          development_build: ${{ inputs.development_build }}
          platform: ${{ env.platform }}
          bot-token: ${{ secrets.TELEGRAM_TOKEN }}
          chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}

  buildForSomePlatforms:
    name: Build for WebGL with itchio channel HTML5
    runs-on: ubuntu-latest
    env:
      dev_build_parameter: ${{ fromJSON('["", "-developmentBuild"]')[inputs.development_build] }}
      itch_channel_prefix: ${{ fromJSON('["", "dev-"]')[inputs.development_build] }}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ env.platform }}
          restore-keys: Library-
      - name: Get variables
        id: variables
        run: |
          version=$(git describe --tags --abbrev=0 --match v[0-9]*)
          version=${version:1}
          echo "::set-output name=version::$version"
      - name: Get project name variable
        id: project_name
        uses: mnicolas94/UnityCICDWorkflows/.github/actions/get-project-name@v1-pre-13
      - name: Download build script
        run: |
          mkdir -p Assets/Editor
          curl 'https://raw.githubusercontent.com/mnicolas94/UnityCICDWorkflows/main/BuildScript.cs' > Assets/Editor/BuildScript.cs
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          buildName: ${{ steps.project_name.outputs.project-name }}
          buildMethod: UnityBuilderAction.BuildScript.Build
          targetPlatform: ${{ env.platform }}
          versioning: Tag
          customParameters: ${{ env.dev_build_parameter }}
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_BUTLER_CREDENTIALS }}
          CHANNEL: ${{ env.itch_channel_prefix }}${{ env.itch_channel }}
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: build/${{ env.platform }}/${{ steps.project_name.outputs.project-name }}
          VERSION: ${{ steps.variables.outputs.version }}
      - name: Send error message if failed
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "⚠️ An error occurred during build."

  sendFinalInformation:
    name: Send final information to Telegram
    needs: buildForSomePlatforms
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: All builds completed succesfully.