name: Android build and deploy android development build on Itch.io and Telegram

on:
  workflow_call:
    inputs:
      development_build:
        required: true
        type: boolean
      cache_tgsession:
        required: false
        default: false
        type: boolean
    secrets:
      TELEGRAM_SESSION:
        required: true
      TELEGRAM_API_ID:
        required: true
      TELEGRAM_API_HASH:
        required: true
      TELEGRAM_CHAT_ID:
        required: true
      TELEGRAM_TOKEN:
        required: true
      UNITY_LICENSE:
        required: true
      ANDROID_KEYSTORE_BASE64:
        required: true
      ANDROID_KEYSTORE_PASS:
        required: true
      ANDROID_KEYALIAS_NAME:
        required: true
      ANDROID_KEYALIAS_PASS:
        required: true
      ITCH_BUTLER_CREDENTIALS:
        required: true
      ITCH_GAME:
        required: true
      ITCH_USER:
        required: true

env:
  platform: Android
  itch_channel: android

jobs:
  sendTagAnnotations:
    name: Send information to Telegram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Send notification message that build process started
        uses: mnicolas94/UnityCICDWorkflows/.github/actions/initial-message@v1
        with:
          development_build: ${{ inputs.development_build }}
          platform: ${{ env.platform }}
          bot-token: ${{ secrets.TELEGRAM_TOKEN }}
          chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}

  buildForSomePlatforms:
    name: Build for Android with itchio channel android
    runs-on: ubuntu-latest
    env:
      dev_build_parameter: ${{ fromJSON('["", "-developmentBuild"]')[inputs.development_build] }}
      itch_channel_prefix: ${{ fromJSON('["", "dev-"]')[inputs.development_build] }}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Get project name variable
        id: project_name
        uses: mnicolas94/UnityCICDWorkflows/.github/actions/get-project-name@v1
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ steps.project_name.outputs.project-name }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ steps.project_name.outputs.project-name }}-
            Library-
      - name: Get version variables
        id: variables
        run: |
          version=$(git describe --tags --abbrev=0 --match v[0-9]*)
          version=${version:1}
          echo "::set-output name=version::$version"
      - name: Download build script
        run: |
          mkdir -p Assets/Editor
          curl 'https://raw.githubusercontent.com/mnicolas94/UnityCICDWorkflows/main/BuildScript.cs' > Assets/Editor/BuildScript.cs
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          buildName: ${{ steps.project_name.outputs.project-name }}
          buildMethod: UnityBuilderAction.BuildScript.Build
          targetPlatform: ${{ env.platform }}
          versioning: Tag
          androidKeystoreName: user.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
          customParameters: ${{ env.dev_build_parameter }}
      - name: Add version to file name
        id: version_in_name
        run: |
          oldfilename="build/Android/${{ steps.project_name.outputs.project-name }}.apk"
          newfilename="build/Android/${{ steps.project_name.outputs.project-name }} ${{ steps.variables.outputs.version }}.apk"
          sudo mv "$oldfilename" "$newfilename"
          echo "::set-output name=filename::$newfilename"
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_BUTLER_CREDENTIALS }}
          CHANNEL: ${{ env.itch_channel_prefix }}${{ env.itch_channel }}
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: ${{ steps.version_in_name.outputs.filename }}
          VERSION: ${{ steps.variables.outputs.version }}
      - name: Check if file size is greater than 50 MB
        id: sizecheck
        run: |
          maxsize=50000000
          filesize=$(stat -c%s "${{ steps.version_in_name.outputs.filename }}")
          echo "The build size is $filesize bytes."
          if (( filesize > maxsize )); then
            echo "::set-output name=bigger::true"
          else
            echo "::set-output name=bigger::false"
          fi
      - name: Send file to telegram
        if: ${{ steps.sizecheck.outputs.bigger == 'false' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Build for ${{ env.itch_channel }} completed
          document: ${{ steps.version_in_name.outputs.filename }}
      - name: Send file to telegram with MTProto API
        if: ${{ steps.sizecheck.outputs.bigger == 'true' }}
        uses: mnicolas94/telegram-file-uploader@main
        with:
          session-name: ${{ secrets.TELEGRAM_SESSION }}
          api-id: ${{ secrets.TELEGRAM_API_ID }}
          api-hash: ${{ secrets.TELEGRAM_API_HASH }}
          bot-token: ${{ secrets.TELEGRAM_TOKEN }}
          chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
          file-path: ${{ steps.version_in_name.outputs.filename }}
          message: Build for ${{ env.itch_channel }} completed
          cache-session: ${{ fromJSON('["false", "true"]')[inputs.cache_tgsession] }}
          reply-request: 'The build size is bigger than 50 MB. Please, reply to this message to give me permission to send you the file'
      - name: Send error message if failed
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "⚠️ An error occurred during build."
  
  sendFinalInformation:
    name: Send final information to Telegram
    needs: buildForSomePlatforms
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: All builds completed succesfully.